---
- name: Setup nginx.
  hosts: all
  become: true
  become_user: root
  remote_user: admin
  vars_files:
    - vars.yaml
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key }}"

- name: Setup Nginx.
  import_playbook: plays/nginx.yaml
# - name: Run sample playbook.
#   import_playbook: plays/sample.yaml
