# This workflow will install Python dependencies, lint the playbooks, and generate execution graphs on Python 3.9. 
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and Generate Graphs.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  create:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint the playbooks.
      run: |
        ./lint
    - name: Generate graphs.
      run: |
        ./make-graphs
    - name: Upload the generated graphs.
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: graphs
        # A file, directory or wildcard pattern that describes what to upload
        path: ./graphs
      
